# Test, and deploy website
language: python

python:
  - 3.8

jobs:
  include:
    - stage: test
      install:
        - pip3 install -r requirements.txt
        - pip3 install -r requirements-dev.txt
      script: pytest
    - stage: push docker image
      services:
        - docker
      script:
        - docker build -t $DOCKER_USERNAME/ezotv:latest .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_USERNAME/ezotv:latest
        - sleep 15 # Make sure it is possible to pull it
    - stage: deploy
      script: skip
      deploy:
        provider: script
        script: curl --silent "$WEBHOOKURL"
        on:
          push: true
          branch: master
          python: 3.8